---
driver:
  name: docker
platforms:
  - name: control-node
    image: "geerlingguy/docker-ubuntu2404-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - control

  - name: worker-node
    image: "geerlingguy/docker-ubuntu2404-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - worker

provisioner:
  name: ansible

verifier:
  name: ansible
